brew "antidote" # ZSH plugin manager
brew "zsh"
brew "zoxide"
brew "vim"
brew "tmux"
brew "jq"
brew "bat"
brew "git"
brew "git-absorb"
brew "diff-so-fancy"
brew "fzf"
brew "ripgrep"
brew "direnv"
brew "awscli"
