setopt null_glob

source /usr/local/share/antigen/antigen.zsh

# Load the oh-my-zsh's library.
# antigen use oh-my-zsh
eval "$(starship init zsh)"

if [[ "$OSTYPE" == "darwin"* ]]; then
  # antigen bundle osx

  # Required for z to work
  source `brew --prefix`/etc/profile.d/z.sh
fi

antigen bundle git
antigen bundle yarn
antigen bundle docker
antigen bundle docker-compose
antigen bundle gitfast
antigen bundle Seinh/git-prune
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-completions

# Tell Antigen that you're done.
antigen apply

autoload -U compinit compdef
compinit

# prefer nvim as $EDITOR
if which nvim > /dev/null; then
  export EDITOR=nvim
  alias vi=nvim
  alias vim=nvim
else
  export EDITOR=vim
  alias nvim=vim
fi
export GIT_EDITOR=$EDITOR
export VISUAL=$EDITOR

# Set GUI editor
export GUI_EDITOR="IntelliJ\ IDEA\ Ultimate"

# Vi mode
bindkey -v '^?' backward-delete-char

# fzf setup
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [ -f ~/.fzf.zsh ]; then
  export FZF_DEFAULT_OPTS=--inline-info
  export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!{.git,node_modules}/*"'
  # To apply the command to CTRL-T as well
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  source ~/.fzf.zsh
  # Re-bind to match most modern editors
  bindkey '\C-p' fzf-file-widget
  # MacOS doesn't use Alt in terminal, so re-bind
  bindkey '\C-o' fzf-cd-widget
fi

if which direnv > /dev/null; then
  # Set up direnv
  eval "$(direnv hook zsh)"
fi

# node (nvm)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# ruby (rvm)
if which rbenv > /dev/null; then
  eval "$(rbenv init -)"
fi

# Enable docker completion for commands such as docker exec -it
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes

# Load aliases
source ~/dotfiles/zsh/aliases.inc.zsh;

# Load custom executable functions
for file in ~/dotfiles/zsh/functions/*.inc.zsh; do
  source "$file"
done

# Load in custom configs
for file in ~/dotfiles/zsh/conf.d/*.inc.zsh; do
  source "$file"
done

